8_apps/Price_alert_app/src/models/__init__.py
__author__ = "esobolie"

8_apps/Price_alert_app/src/__init__.py
__author__ = "esobolie"

8_apps/Price_alert_app/src/app.py
from flask import Flask, render_template

from src.common.database import Database

from src.models.users.views import user_blueprint
from src.models.alerts.views import alert_blueprint
from src.models.stores.views import store_blueprint

__author__ = "esobolie"

app = Flask(__name__)
app.config.from_object("config")
app.secret_key = "ySDAZb4C6qYkkXbXzhUF2aHY"


@app.before_first_request
def init_db():
    Database.initialize()


@app.route("/")
def home():
    return render_template("home.html")


app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")
app.register_blueprint(store_blueprint, url_prefix="/stores")

8_apps/Price_alert_app/src/common/__init__.py
__author__ = "esobolie"

8_apps/Price_alert_app/src/models/alerts/__init__.py
__author__ = "esobolie"

8_apps/Price_alert_app/src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators

__author__ = "esobolie"

alert_blueprint = Blueprint("alerts", __name__)


@alert_blueprint.route("/new", methods=["GET", "POST"])
@user_decorators.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()

    return render_template('alerts/new_alert.html')


@alert_blueprint.route("/edit/<string:alert_id>", methods=["GET", "POST"])
@user_decorators.requires_login
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    if request.method == 'POST':
        price_limit = float(request.form('price_limit'))

        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for('users.user_alerts'))

    return render_template('alerts/edit_alert.html', alert=alert)


@alert_blueprint.route("/deactivate/<string:alert_id>")
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route("/delete/<string:alert_id>")
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route("/activate/<string:alert_id>")
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route("/<string:alert_id>")
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('alerts/alert.html', alert=alert)


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

8_apps/Price_alert_app/src/models/items/__init__.py
__author__ = "esobolie"

8_apps/Price_alert_app/src/models/items/views.py
from flask import Blueprint
__author__ = "esobolie"

item_blueprint = Blueprint("items", __name__)

@item_blueprint.route("/item/<string:name>")
def item_page():
    pass

# @item_blueprint.route("/load")
# def load_item():
#     """
#     Load an item's data using the store and return JSON representation of it
#     :return:
#     """
#     pass

8_apps/Price_alert_app/src/models/stores/__init__.py
__author__ = "esobolie"

8_apps/Price_alert_app/src/models/stores/views.py
from flask import Blueprint, render_template, request, json, redirect, url_for
import src.models.users.decorators as user_decorators
from src.models.stores.store import Store

__author__ = "esobolie"

store_blueprint = Blueprint("stores", __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_index.html', stores=stores)


@store_blueprint.route("/store/<string:store_id>")
def store_page(store_id):
    return render_template('stores/store.html', store=Store.get_by_id(store_id))


@store_blueprint.route('/edit/<string:store_id>', methods=["GET", "POST"])
@user_decorators.requires_admin_permissions
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == "POST":
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))
    return render_template('/stores/edit_store.html', store=store)


@store_blueprint.route('/delete/<string:store_id>')
@user_decorators.requires_admin_permissions
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index'))


@store_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions
def create_store():
    if request.method == "POST":
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/new_store.html')

8_apps/Price_alert_app/src/models/users/__init__.py
__author__ = "esobolie"

8_apps/Price_alert_app/src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect

import src.models.users.errors as UserErrors
from src.models.users.user import User
import src.models.users.decorators as user_decorators

__author__ = "esobolie"

user_blueprint = Blueprint("users", __name__)


@user_blueprint.route("/login", methods=["GET", "POST"])
def login_user():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        try:
            if User.is_login_valid(email, password):
                session["email"] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("/users/login.html")


@user_blueprint.route("/register", methods=["GET", "POST"])
def register_user():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        try:
            if User.register_user(email, password):
                session["email"] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("/users/register.html")


@user_blueprint.route("/alerts")
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts = user.get_alerts()
    return render_template('users/alerts.html', alerts=alerts)


@user_blueprint.route("/logout")
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))


@user_blueprint.route("/check_alerts/<string:user_id>")
def check_user_alerts(user_id):
    pass

8_apps/Price_alert_app/src/templates/alerts/alert.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Alert
        <small>for {{ alert.item.name }}</small>
    </h1>
</div>
<p>Last price found <strong>{{ alert.item.price }}</strong></p>
<p>Last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%Y at %H-%M") }}</strong></p>
<div class="panel panel-default">
    <div class="panel-body">
        <a class="btn btn-default" href="{{ alert.item.url }}" role="button">Visit site</a>
        <a class="btn btn-warning" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit alert</a>
        {% if alert.active %}
            <a class="btn btn-danger" href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}" role="button">Deactivate alert</a>
        {% else %}
            <a class="btn btn-success" href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}" role="button">Activate alert</a>
            <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" role="button">Delete alert</a>
        {% endif %}
        <a class="btn btn-warning" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}" role="button">Check alert price</a>
    </div>
</div>

{% endblock %}

8_apps/Price_alert_app/src/templates/alerts/edit_alert.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Edit Alert
        <small>Create new alert for your shop</small>
    </h1>
</div>
<div class="form-size">
    <form method="post">
        <div class="form-group">
            <label for="name">Alert/Item Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name" disabled>
        </div>
        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="http://..." disabled>
        </div>
        <div class="form-group">
            <label for="price_limit">Price limit alert</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="100" value="{{ alert.price_limit }}" aria-describedby="priceLimitBlock">
            <p id="priceLimitBlock" class="help-block">Will send you email when price goes under this</p>
            <button type="submit" class="btn btn-default">Update</button>
        </div>
    </form>
</div>
{% endblock %}

8_apps/Price_alert_app/src/templates/alerts/new_alert.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Create Alert
        <small>Create new alert for your shop</small>
    </h1>
</div>
<div class="form-size">
    <form method="post">
        <div class="form-group">
            <label for="name">Alert/Item Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
        </div>
        <div class="form-group">
            <label for="price_limit">Price limit alert</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="100" aria-describedby="priceLimitBlock">
            <p id="priceLimitBlock" class="help-block">Will send you email when price goes under this</p>
            <button type="submit" class="btn btn-default">Create</button>
        </div>
    </form>
</div>
{% endblock %}

8_apps/Price_alert_app/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing Service</title>

    {% include "html_dependencies.html" %}

</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" title="home">Pricing</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('stores.index') }}">Stores</a></li>
            </ul>
            {% if session['email'] %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.user_alerts')}}"><span class="glyphicon glyphicon-alert"></span> Your alerts</a></li>
                    <li><a href="{{ url_for('users.logout_user')}}"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.register_user')}}"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
                    <li><a href="{{ url_for('users.login_user')}}"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
<div class="content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

8_apps/Price_alert_app/src/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <h1>Pricing service!</h1>
    <p>Watch prices!</p>
    <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign up</a></p>
</div>
{% endblock %}

8_apps/Price_alert_app/src/templates/html_dependencies.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

8_apps/Price_alert_app/src/templates/stores/edit_store.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Edit store
    </h1>
</div>
<div class="form-size">
    <form method="post">
        <div class="form-group">
            <label for="name">Store name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Store name" value="{{ store.name }}">
        </div>
        <div class="form-group">
            <label for="url_prefix">Store URL prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." value="{{ store.url_prefix }}" aria-describedby="storeURLPrefixHelp">
            <span id="storeURLPrefixHelp" class="help-block">What characters do URLs of all items in this online store start with?</span>
        </div>
        <div class="form-group">
            <label for="tag_name">Store tag name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="{{ store.tag_name }}" aria-describedby="storeTagNameHelp">
            <span id="storeTagNameHelp" class="help-block">What what is the html tag of the item that contains the item price? (usually <code>span</code>)</span>
        </div>
        <div class="form-group">
            <label for="query">Search query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder='{ "id": "price-now" }' value="{{ store.query | tojson }}" aria-describedby="queryHelpBlock">
            <span id="queryHelpBlock" class="help-block">What qson query we have to do to find the specific tag with the price? Remember to use double quotation marks</span>

        </div>
        <button class="btn btn-warning" type="submit">Update</button>
    </form>
</div>
{% endblock %}

8_apps/Price_alert_app/src/templates/stores/new_store.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Create store
    </h1>
</div>
<div class="form-size">
    <form method="post">
        <div class="form-group">
            <label for="name">Store name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Store name">
        </div>
        <div class="form-group">
            <label for="url_prefix">Store URL prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." aria-describedby="storeURLPrefixHelp">
            <span id="storeURLPrefixHelp" class="help-block">What characters do URLs of all items in this online store start with?</span>
        </div>
        <div class="form-group">
            <label for="tag_name">Store tag name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="span" aria-describedby="storeTagNameHelp">
            <span id="storeTagNameHelp" class="help-block">What what is the html tag of the item that contains the item price? (usually <code>span</code>)</span>
        </div>
        <div class="form-group">
            <label for="query">Search query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder='{ "id": "price-now" }' value='{ "id": "price-now" }' aria-describedby="queryHelpBlock">
            <span id="queryHelpBlock" class="help-block">What qson query we have to do to find the specific tag with the price? Remember to use double quotation marks</span>

        </div>
        <button class="btn btn-default" type="submit">Create</button>
    </form>
</div>
{% endblock %}

8_apps/Price_alert_app/src/templates/stores/store.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Store
        <small>{{ store.name }}</small>
    </h1>
</div>
<p>all url in this store should start with <strong>{{ store.url_prefix }}</strong></p>

{% if session['email'] in config.ADMINS %}
<div class="panel panel-default">
    <div class="panel-body">
        <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">Edit
            store</a>
        <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Delete
            store</a>
    </div>
</div>
{% endif %}

{% endblock %}

8_apps/Price_alert_app/src/templates/stores/store_index.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Stores<small> list of supported stores</small></h1>
</div>
<div class="list-group">
    {% for store in stores %}
        <a href='{{ url_for("stores.store_page", store_id=store._id) }}' class='list-group-item'>
        <h4 class='list-group-item-title'>{{ store.name }}</h4>
            <p class='list-group-item-text'>all url in this store should start with <strong>{{ store.url_prefix }}</strong> </p>
        </a>
    {% endfor %}
</div>
{% if session['email'] in config.ADMINS %}
<a class="btn btn-default" href="{{ url_for('stores.create_store') }}">
    <span class="glyphicon glyphicon-plus"></span>Create new
</a>
{% endif %}
{% endblock %}

8_apps/Price_alert_app/src/templates/stores/store_list.html
{% extends "base.html" %}
{% block content %}
<p>...Nothing here yet</p>
{% endblock %}

8_apps/Price_alert_app/src/templates/users/alerts.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Alerts
        <small>showing already existing alerts</small>
    </h1>
</div>
<div class="list-group">
    {% for alert in alerts %}
    <a href="{{ url_for('alerts.get_alert_page', alert_id=alert._id) }}" class="list-group-item {{ ' list-group-item-warning' if not alert.active else '' }}">
        <h4 class="list-group-item-heading">{{ '<span class="glyphicon glyphicon-remove-circle"></span>' if not alert.active else '' }}Alert for {{ alert.item.name }}</h4>
        <p class="list-group-item-text">Last price found <strong>{{ alert.item.price }}</strong><br/>
            Last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%Y at %H-%M") }}</strong></p>
    </a>
    {% endfor %}
</div>
<a class="btn btn-success" href="{{ url_for('alerts.create_alert') }}"><span class="glyphicon glyphicon-plus"></span>
    Create new</a>
{% endblock %}

8_apps/Price_alert_app/src/templates/users/login.html
{% extends "base.html" %}
{% block content %}
<div class="form-size">
    <form action="{{ url_for('users.login_user') }}" method="post">
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-default">Login</button>
    </form>
</div>
{% endblock %}

8_apps/Price_alert_app/src/templates/users/register.html
{% extends "base.html" %}
{% block content %}
<div class="form-size">
    <form action="{{ url_for('users.register_user') }}" method="post">
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-default">Sign up</button>
    </form>
</div>
{% endblock %}